spring:
    data:
        mongodb:
            host: mongodbecommerce
            port: 27017
            database: eco_customer_db
            username: root
            password: pass
            authentication-database: admin
server:
    port: 8091